[project]
name = "shardspace"
version = "0.0.1"
authors = [
  { name="Matthew Gunther", email="spottedalbinojumpingfrog@gmail.com" },
]
description = "A hobby package for orbits in the Shardspace D&D setting"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/pypa/shardspace"
Issues = "https://github.com/pypa/shardspace/issues"